---
driver:
  forward_agent: yes
  name: vagrant
  vm_hostname: false # do not bother trying to change the hostname (sometimes fails)
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm

provisioner:
  name: chef_zero

platforms:
  - name: win2012r2
    driver_config:
      box: kensykora/windows_2012_r2_standard
      box_url: kensykora/windows_2012_r2_standard

suites:
- name: default
  run_list:
    - 'recipe[fourthcoffee]'
  attributes:
    fourthcoffee:
      install_method: _dsc
